version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: "no"
    volumes:
    - apollo_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: "no"
    depends_on:
      - postgres
  node:
    build: ./
    image: vkp-api
    ports:
      - "8082:8082"
    depends_on:
      - postgres
volumes:
  apollo_db_data:

